[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "unibase"
version = "0.1.0"
description = "Official Python SDK for Unibase BaaS"
readme = "README.md"
authors = [
    { name = "Bharat (Unibase Team)" }
]
requires-python = ">=3.7"
dependencies = [
    "requests>=2.25.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "responses"
]

[project.urls]
Homepage = "https://github.com/BhArAtbK-alt/Unibase-client"
